name: Build
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.spec.js"
      - ".idea"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/release.yml"
  pull_request:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tags:
          description: 'Manual run'

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: "bash"

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths: '[".github/workflows/release.yml","app/package.json","app/package-lock.json","app/electron-builder.config.js","app/get_version.js","app/src/vite_main.config.js","app/src/vite_renderer.config.js","app/src/scripts/*","server/build_server.sh","server/poetry.lock","server/pyoxidizer.bzl","server/pyproject.toml","server/requirements.txt"]'

  get_metadata:
    runs-on: ubuntu-latest
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' || github.event_name == 'push' }}
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Echo branch name
        shell: bash
        run: echo "Currently on branch '${{ steps.extract_branch.outputs.branch }}'"

  upload_artifacts:
    name: Build
    needs: [get_metadata, pre_job]

    strategy:
      matrix:
        os: [macos-10.15, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Build server
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/
          key: ${{ runner.os }}-cargo

      - uses: actions-rs/toolchain@v1
        name: Install rust
        with:
          toolchain: stable

      - name: Install pyoxidizer fork
        run: cargo install pyoxidizer

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Build
        run: ./server/build_server.sh
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: npm --prefix app/ ci

      - name: Delete outdated drafts
        uses: hugo19941994/delete-draft-releases@v1.0.0
        continue-on-error: true
        with:
          threshold: 5d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # From https://github.com/samuelmeuli/action-electron-builder/issues/42
      - name: Install libarchive-tools for pacman build # Related https://github.com/electron-userland/electron-builder/issues/4181
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install libarchive-tools

      # Compile app and upload artifacts
      - name: Compile & release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          build_script_name: build
          package_root: app/
          args: --config electron-builder.config.js

          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is in the main branch and this does not run on a PR, release
          release: ${{ github.event_name == 'push' && needs.get_metadata.outputs.branch == 'main' }}

          # Sometimes the build may fail due to a connection problem with Apple, GitHub, etc. servers.
          # This option will restart the build as many attempts as possible
          max_attempts: 3

          # Code Signing params

          # Base64-encoded code signing certificate for Windows
          # windows_certs: ''

          # Password for decrypting `windows_certs`
          # windows_certs_password: ''

          # Base64-encoded code signing certificate for macOS
          mac_certs: ${{ secrets.mac_certs }}
          # Password for decrypting `mac_certs`
          mac_certs_password: ${{ secrets.mac_certs_password }}

  finalize:
    needs: [upload_artifacts]
    if: always()
    # && ${{ needs.upload_artifacts.result == 'skipped' || needs.upload_artifacts.result == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Check that build succeeded or was skipped
        shell: bash
        run: "[[ '${{needs.upload_artifacts.result}}' == 'success'  || '${{needs.upload_artifacts.result}}' == 'skipped' ]]"
